app/modules/register/forms.py
from flask_wtf import FlaskForm

from wtforms import PasswordField, BooleanField, SubmitField, EmailField, StringField, DateField
from wtforms.validators import DataRequired, Email, Length, EqualTo


class LoginForm(FlaskForm):
    email = EmailField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember me')
    submit = SubmitField('Log in')


class RegisterForm(FlaskForm):
    name = StringField('Your name', validators=[DataRequired()])
    surname = StringField('Your surname', validators=[DataRequired()])
    email = EmailField('Email', validators=[DataRequired(), Email(message=None), Length(min=6, max=40)])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=8, max=40)])
    password_again = PasswordField('Repeat password', validators=[DataRequired(),
        EqualTo("password", message="Passwords are different.")])
    submit = SubmitField('Sign up')

app/modules/register/__init__.py
from flask import Blueprint

module = Blueprint('register', __name__, url_prefix ='/register')

from app.modules.register import routes

app/modules/register/routes.py
from flask import render_template, make_response, redirect, url_for, request
from flask_login import login_user, login_required, logout_user, current_user

from app.models import User
from app import db, logger
from . import module
from .forms import RegisterForm, LoginForm


# Registration user profile
@module.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return make_response(redirect(url_for('main.main')))

    form = RegisterForm()
    if form.validate_on_submit():
        logger.debug(f"Processing registration form for email: {form.email.data}")
        if form.password.data != form.password_again.data:
            return render_template('register/register.html', title='Регистрация', form=form,
                                   message='Пароли разные!')
        if User.query.filter_by(email=form.email.data).first():
            return render_template('register/register.html', title='Регистрация', form=form,
                                   message='Такой пользователь уже существует')

        try:
            user = User(
                name=f"{form.name.data} {form.surname.data}",
                email=form.email.data,
            )
            user.set_password(form.password.data)
            db.session.add(user)
            db.session.commit()
            logger.info(f"User {form.email.data} successfully registered.")
            return redirect(url_for('register.login'))
        except Exception as e:
            logger.error(f"Error registering user with email {form.email.data}: {e}")
            db.session.rollback()
            return render_template('register/register.html', title='Регистрация', form=form,
                                   message='Произошла непредвиденная ошибка.')

    return render_template('register/register.html', title='Регистрация', form=form)


# Logging
@module.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return make_response(redirect(url_for('main.main')))

    form = LoginForm()
    if form.validate_on_submit():
        logger.debug(f"Processing login form for email: {form.email.data}")
        try:
            user = User.query.filter_by(email=form.email.data).first()
            if user and user.check_password(form.password.data):
                login_user(user, remember=form.remember_me.data)
                return make_response(redirect(url_for('main.main')))

            return render_template('register/login.html', title='Вход', message='Ошибка в логине или пароле',
                                   form=form)
        except Exception as e:
            logger.error(f"Error during login: {e}")
            return render_template('register/login.html', title='Вход', form=form,
                                   message='Произошла непредвиденная ошибка')

    return render_template('register/login.html', title='Вход', form=form)


# Logout
@module.route('/logout')
@login_required
def logout():
    logout_user()
    return make_response(redirect(url_for('register.login')))

app/templates/register/login.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{{ title }}</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/logo.png') }}" type="image/png">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
</head>
<body>
<main class="form-signin">
  <form action="" method="post">
    {{ form.hidden_tag() }}
    <a href="/"><img src="{{ url_for('static', filename='img/logo.png') }}" class="mt-4" width="150px" alt="Logo"></a>
    <h1 class="mb-4 mt-4 text1">Вход</h1>

    <div class="form-floating mb-3">
        {{ form.email(class="form-control", id="floatingEmail", placeholder="name@example.com", autocomplete="email") }}
        <label for="floatingEmail">Почта</label>
        {% for error in form.email.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </div>

    <div class="form-floating mb-3">
        {{ form.password(class="form-control", id="floatingPassword", placeholder='Password', autocomplete="current-password") }}
        <label for="floatingPassword">Пароль</label>
        {% for error in form.password.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </div>

    <p style="margin: 10px;">{{ form.remember_me() }} Запомнить меня</p>

    <button class="btn btn-primary w-100 py-2 fs-5 fw-bold" type="submit">Войти</button>

    <p class="mt-3">Ещё нет аккаунта? <a href="{{ url_for('register.register') }}" class="fw-bold login-link">Зарегистрироваться</a></p>

    <div>{{ message }}</div>
  </form>
</main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

app/templates/register/register.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>{{ title }}</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/logo.png') }}" type="image/png">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
</head>
<body class="d-flex align-items-center py-4 bg-light">
<main class="form-signin w-100 m-auto">
  <form action="" method="post">
    {{ form.hidden_tag() }}
    <a href="/" class="logo-container"><img src="{{ url_for('static', filename='img/logo.png') }}" class="mt-4" width="150px"></a>
    <h1 class="mb-4 mt-4 text1">Регистрация</h1>

    <div class="form-floating mb-3">
        {{ form.name(class="form-control", id="floatingName", placeholder='Name') }}
        <label for="floatingName">Имя</label>
        {% for error in form.name.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </div>

    <div class="form-floating mb-3">
        {{ form.surname(class="form-control", id="floatingSurname", placeholder='Surname') }}
        <label for="floatingSurname">Фамилия</label>
        {% for error in form.surname.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </div>

    <div class="form-floating mb-3">
        {{ form.email(class="form-control", id="floatingEmail", placeholder='name@example.com') }}
        <label for="floatingEmail">Почта</label>
        {% for error in form.email.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </div>

    <div class="form-floating mb-3">
        {{ form.password(class="form-control", id="floatingPassword", placeholder='Password') }}
        <label for="floatingPassword">Пароль</label>
        {% for error in form.password.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </div>

    <div class="form-floating mb-3">
        {{ form.password_again(class="form-control", id="floatingPasswordAgain", placeholder='Password again') }}
        <label for="floatingPasswordAgain">Повторите пароль</label>
        {% for error in form.password_again.errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    </div>

    <button class="btn btn-primary w-100 py-2 fs-5 fw-bold" type="submit">Зарегистрироваться</button>

    <p style="margin-top:10px">Уже есть аккаунт? <a href="{{ url_for('register.login') }}" class="fw-bold login-link">Войти</a></p>
    <div>{{ message }}</div>
  </form>
</main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>